# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

env:
  - BUILD_ENV={{if index .Env "BUILD_ENV"}}{{.Env.BUILD_ENV}}{{else}}production{{end}}

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X github.com/can3p/kleiner/generated/buildinfo.buildDate={{.CommitDate}}
      - -X github.com/can3p/kleiner/generated/buildinfo.buildVersion={{.Version}}
      - -X github.com/can3p/kleiner/generated/buildinfo.commit={{.ShortCommit}}
    tags:
      - "{{.Env.BUILD_ENV}}"

archives:
  - id: linux
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_Linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    builds: [linux]
    files: [only-the-binary*]
    wrap_in_directory: false
    format: tar.gz

  - id: macos
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    builds: [macos]
    files: [only-the-binary*]
    wrap_in_directory: false
    format: tar.gz

  - id: windows
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_Windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    builds: [windows]
    files: [wintun.dll]
    wrap_in_directory: false
    format: zip
